CREATE TABLE `consultations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`patient_hash` text(64) NOT NULL,
	`consultation_date` text(30) NOT NULL,
	`created_at` text(30) DEFAULT (datetime('now')),
	`language` text(10) DEFAULT 'es' NOT NULL,
	`patient_age` integer,
	`patient_gender` text(10),
	`symptoms` text NOT NULL,
	`diagnosis` text,
	`syndrome` text NOT NULL,
	`points` text,
	`herbs` text,
	`rationale` text,
	`kant_status` text(10) NOT NULL,
	`kant_score` integer DEFAULT 0 NOT NULL,
	`kant_alerts` text,
	`kant_contraindications` text,
	`kant_audit_trail` text,
	`rag_citations` text,
	`llm_model` text(50) NOT NULL,
	`foucault_pdf_path` text,
	`foucault_forensic_hash` text(64),
	`foucault_empathic_hash` text(64),
	`regulatory_framework` text(20) DEFAULT 'AHPRA',
	`is_test` integer DEFAULT false,
	`ahpra_flags` text,
	`chain_of_custody` text,
	`practitioner_name` text,
	`practitioner_registration` text,
	`practitioner_qualification` text,
	`practitioner_clinic` text,
	`practitioner_address` text,
	`practitioner_phone` text,
	`complexion` text,
	`spirit` text,
	`body_shape` text,
	`posture` text,
	`skin_condition` text,
	`hair_condition` text,
	`eyes` text,
	`nails` text,
	`tongue_body_color` text,
	`tongue_body_shape` text,
	`tongue_coating_color` text,
	`tongue_coating_thickness` text,
	`tongue_coating_distribution` text,
	`tongue_moisture` text,
	`tongue_sublingual_veins` text,
	`tongue_notes` text,
	`pulse_left_cun` text,
	`pulse_left_guan` text,
	`pulse_left_chi` text,
	`pulse_right_cun` text,
	`pulse_right_guan` text,
	`pulse_right_chi` text,
	`pulse_depth` text,
	`pulse_rate` text,
	`pulse_rhythm` text,
	`pulse_quality` text,
	`pulse_overall` text,
	`pulse_notes` text,
	`ryodoraku_lung` integer,
	`ryodoraku_pericardium` integer,
	`ryodoraku_heart` integer,
	`ryodoraku_small_intestine` integer,
	`ryodoraku_triple_warmer` integer,
	`ryodoraku_large_intestine` integer,
	`ryodoraku_spleen` integer,
	`ryodoraku_liver` integer,
	`ryodoraku_kidney` integer,
	`ryodoraku_bladder` integer,
	`ryodoraku_stomach` integer,
	`ryodoraku_gallbladder` integer,
	`ryodoraku_notes` text,
	`abdomen_overall` text,
	`abdomen_sho` text,
	`abdomen_tenderness` text,
	`abdomen_tension` text,
	`abdomen_temperature` text,
	`abdomen_water_sound` text,
	`abdomen_notes` text,
	`bian_zheng` text,
	`zang_fu_pattern` text,
	`ba_gang` text,
	`qi_blood_fluid` text,
	`channel_pattern` text,
	`disease_mechanism` text,
	`western_diagnosis` text,
	`treatment_principle` text,
	`treatment_method` text,
	`points_execution` text,
	`acupuncture_needle_type` text,
	`acupuncture_needle_count` integer,
	`acupuncture_duration` text,
	`acupuncture_frequency` text,
	`acupuncture_total_sessions` integer,
	`acupuncture_sequence` text,
	`acupuncture_deqi` text,
	`acupuncture_notes` text,
	`moxibustion_type` text,
	`moxibustion_points` text,
	`moxibustion_duration` text,
	`moxibustion_frequency` text,
	`moxibustion_contraindications` text,
	`cupping_type` text,
	`cupping_location` text,
	`cupping_duration` text,
	`cupping_frequency` text,
	`cupping_notes` text,
	`tuina_techniques` text,
	`tuina_duration` text,
	`tuina_frequency` text,
	`tuina_contraindications` text,
	`dietary_advice` text,
	`dietary_avoid` text,
	`dietary_constitution` text,
	`exercise_type` text,
	`exercise_routine` text,
	`exercise_contraindications` text,
	`herbal_formula` text,
	`herbal_ingredients` text,
	`herbal_modifications` text,
	`herbal_dosage` text,
	`herbal_administration` text,
	`herbal_duration` text,
	`herbal_frequency` text,
	`herbal_contraindications` text,
	`herbal_tga_status` text,
	`herbal_ahpra_warning` text,
	`prognosis` text,
	`follow_up_plan` text,
	`expected_outcomes` text,
	`red_flags` text,
	`referral_needed` integer,
	`referral_to` text,
	`referral_reason` text,
	`informed_consent` integer,
	`consent_date` text,
	`patient_signature` text,
	`practitioner_signature` text,
	`risk_acknowledged` integer,
	`privacy_acknowledged` integer,
	`foucault_version` text,
	`rag_chunks_used` text,
	`openrouter_model` text,
	`generation_timestamp` text,
	`empathic_narrative` text,
	`home_care_instructions` text
);
--> statement-breakpoint
CREATE INDEX `idx_patient_hash` ON `consultations` (`patient_hash`);--> statement-breakpoint
CREATE INDEX `idx_consultation_date` ON `consultations` (`consultation_date`);--> statement-breakpoint
CREATE INDEX `idx_kant_status` ON `consultations` (`kant_status`);--> statement-breakpoint
CREATE INDEX `idx_patient_date` ON `consultations` (`patient_hash`,`consultation_date`);--> statement-breakpoint
CREATE INDEX `idx_is_test` ON `consultations` (`is_test`);--> statement-breakpoint
CREATE INDEX `idx_language` ON `consultations` (`language`);--> statement-breakpoint
CREATE INDEX `idx_forensic_hash` ON `consultations` (`foucault_forensic_hash`);--> statement-breakpoint
CREATE INDEX `idx_empathic_hash` ON `consultations` (`foucault_empathic_hash`);--> statement-breakpoint
CREATE INDEX `idx_practitioner` ON `consultations` (`practitioner_registration`);--> statement-breakpoint
CREATE INDEX `idx_referral` ON `consultations` (`referral_needed`);